package dto;

import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SchedulePostDto {
    private int postId;
    private String title;
    private String meetDate;
    private String meetTime;
    private int currentPeople; // varchar2이므로 문자열로 처리
    private int maxPeople; // varchar2이므로 문자열로 처리
}

/*
CREATE TABLE CHAT_PARTICIPANTS (
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  POST_ID NUMBER,
  USER_ID VARCHAR2(50),
  CHANNEL_NAME VARCHAR2(100),
  JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (POST_ID) REFERENCES SCHEDULE_POST(POST_ID)
);
*/